### ISSUE TITLE
Scrollable tables don't show content on mobile

### ISSUE THREAD

**Issue by jfabellera** [jfabellera/billy#31]
Antd does not have an easy API to have tables to stretch to their parent container, so the css has to be modified for antd-tables. Making the table scrollable makes it worse, since there is a hacky way to make scrolling in a stretchable table work i.e. setting the height of the table-body to `0px` even though it is definitely not `0px`. This works on desktop browsers, but not for mobile browsers. The only solution would be to have a fixed height, but that doesn't work well as being responsive.

**Comment by carlaequihua** [comment]
Table is not populated on Safari.

**Comment by jfabellera** [comment]
![image](https://user-images.githubusercontent.com/15681113/107264440-952d7900-6a08-11eb-9fb9-730acbea23b9.png)
The tables work on Android mobile. Might be a webkit issue or whatever Apple uses

**Comment by walterimaican** [comment]
Issue occurs on both Chrome and Safari on my iPhone

![IMG_3214](https://user-images.githubusercontent.com/65641903/107266113-b0998380-6a0a-11eb-884c-28f164d70d57.jpeg)
![IMG_3212](https://user-images.githubusercontent.com/65641903/107266119-b2fbdd80-6a0a-11eb-9d20-65c5d4b8c40b.jpg)
